#!/usr/bin/env bash

I=20 # number of iterations

mysqladmin -c$I -i1 processlist | \
                                grep -v -i -E 'Id[[:space:]]*\|[[:space:]]*user' | \
                                grep -v root | \
                                sed '/^\+/d' | \
                                sed '/^$/d' | \
                                cut -d'|' -f3 | \
                                sort | \
                                uniq -c | \
                                sort -rn | \
                                head